version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_arm64
      - linux_amd64
      - windows_amd64
    ldflags:
      - -s
      - -w
    binary: >-
      fast-image
    main: .
archives:
  - format: tar.gz
    name_template: "fast-image_{{ .Target }}"
    format_overrides:
      - goos: windows
        format: zip
